### ISSUE TITLE
Vibrancy gets lost upon navigation

### ISSUE THREAD

**Issue by oskarkrawczyk** [arkenthera/electron-vibrancy#8] opened 2016-10-30 10:33 UTC
I'm still in the rains of battle with getting vibrancy working in my app. I'm currently having an issue when I switch pages in `BrowserWindow` (or run `mainWindow.loadURL` more than once), the vibrancy gets lost (https://v.usetapes.com/YzrDwIEP42). Unfortunately I cannot reproduce this behavior in the test app.

What I've noticed in debug, is that `ViewId` has the value of `-1` which feels incorrect (?)

```
2016-10-30 11:27:41.220 Electron[13183:303052] X:0 Y:0 W:1260 H:600 Resize:2 Mat:9 ViewId: -1
```

**Comment by arkenthera** [comment] 2016-10-30 10:50
That logging is for verifying the `options` object being read correctly on the C++ side,so `SetVibrancy` doesnt pass a `ViewId`, hence the `-1`. Nothing wrong there.  
I'll have to test this myself but multiple calls to `loadURL` might reset the underlying `NSView*` and since the `NSVisualEffectView` depends on the `NSView` vibrancy getting lost should be expected. I'll try this and get back to you again.

**Comment by arkenthera** [comment] 2016-10-30 11:34
Hey, unfortunately I couldnt reproduce it. I called `loadURL` multiple times and set up a simple navigation in HTML side to navigate around but vibrancy stayed. Though something crossed my mind, is it possible that (in the video) the page you're navigating to doesnt have transparency? (i.e. alpha == 1)

**Comment by arkenthera** [comment] 2016-11-05 15:04
Closing until more info from @oskarkrawczyk

**Closed by arkenthera** 2016-11-05 15:04 UTC
Labels: need more info
